<template>
    <v-card class="ma-3">
        <!--@submit.prevent associates login to the form-->
        <form class="ma-1">
            # leagueId (required) is an integer auto-generated by the database, the API requires a valid number be passed to it, but doesn't do anything with it.  I should fix this in a future PR.
            # leagueName (required) is a string, keep it under 255 characters
            # description (required) is a string, keep it under 255 characters
            # sportId (required) is an integer, it is the ID number of the sport this league belongs to.  There is no validation if the sportId exists.
            # ageMin is an integer value
            # ageMax is an integer value
            # coed is a boolean value, 0 or false for not a coed league, and 1 or true for a coed league
            # teamMin is an integer value
            # teamMax is an integer value
            # leagueSchedule is a string, keep it under 255 characters
            # leagueRules is a string, keep it under 255 characters
            ### All fields not specified as required are optional
            <!--Register New League-->
                <v-text-field
                        label="League Name"
                        required
                        v-model="league.leagueName">
                </v-text-field>
                <v-text-field
                        label="Description"
                        required
                        v-model="league.description">
                </v-text-field>
                <v-text-field
                        label="Enter Organization Name"
                        required
                        v-model="league.orgname">
                </v-text-field>
                <v-text-field
                        label="Create New Email"
                        required
                        v-model="league.email">
                </v-text-field>
                <v-text-field
                        label="Create New Phone"
                        required
                        v-model="league.phone">
                </v-text-field>
                <v-text-field
                        label="Create New Address"
                        required
                        v-model="league.address">
                </v-text-field>
            <v-btn v-if="!settings.editleague && !settings.registerleague" color="primary" to="/" type="submit"
                   @click="login(league)">
                CREATE LEAGUE
            </v-btn>
            <v-btn @click="cancel">cancel</v-btn>
        </form>
    </v-card>
</template>

<script>
    export default {
        data: () => ({
        }),
        computed: {
            settings() {
                return this.$store.state.settings;
            }
        },
        methods: {
            createLeague: function (league) {
                console.log(league);
                this.$store.dispatch('createLeague', league)
                    .then(() => console.log('creating leaugue'))
                    .catch(err => console.log(err))
            },
            updateLeague: function (league) {

            },
            cancel: function () {
                this.$store.dispatch('cancelLeagueForm')
                    .then(() => this.$router.push('/'))
                    .catch(err => console.log(err))
            }
        }
    }
</script>

<style>
</style>